name: ASW

on: [workflow_dispatch]

env:
  SOLUTION_FILE_PATH: src/Game_SWARM-2010.sln

  BUILD_CONFIGURATION: Release

jobs:
  build-windows-amd64:
    runs-on: windows-2019

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Generate SLN
      run: |
        ./src/creategameprojects2010.bat

    - name: Build windows-amd64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git submodule init && git submodule update
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Executables
      uses: actions/upload-artifact@v3
      with:
        name: asw_build
        path: |
          src/bin/*
